Yªηx-®ιάjΧΆλiΊΪ+§j[h‘ιάΆινηnµN‹Z–‹­¦λew¬Υ¥µΑ½ΙΠμ‰•™½Ι•… °‘•ΝΙ¥‰”°•αΑ•Π°¥Π°Ω¤τ™Ι½΄€Ω¥Ρ•ΝΠ()½ΉΝΠ™½ΥΝ=Α•ΉM•ΝΝ¥½Έ€τΩ¤Ή™Έ ¤)½ΉΝΠ™Ι½ΉΡ5…¥Ή%™M•±•Ρ•€τΩ¤Ή™Έ ΅ΝΡ½Ι•‘M•ΝΝ¥½Ή%θΝΣzΦΪ$z{-®ιάjΧpect(openSessionTile).not.toHaveBeenCalled()
    expect(navigate).not.toHaveBeenCalled()
    expect(focusOpenSession).not.toHaveBeenCalled()
  })
})
